services:
  - type: web
    name: orange-shop
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node server.js"
    healthCheckPath: /api/products
    envVars:
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_czxE5VXl4PZT@ep-rapid-leaf-a5tgmamp-pooler.us-east-2.aws.neon.tech/neondb?sslmode=require
      - key: ALLOWED_ORIGIN
        value: https://orange-shop-rrl.pages.dev
